services:
    app:
        container_name: image-bucket
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '10001:10001'
        volumes:
            - ./images:/images
        restart: always
