services:
    app:
        container_name: image-bucket
        image: 'image-bucket:latest'
        ports:
            - '10001:10001'
        volumes:
            - ./images:/images
        restart: always
